// 和谐交易顾问 · 预生成数据
// 生成时间: 2026-07-07 11:44 CST
// 数据来源: 东方财富API + 三框架分析引擎
// 此文件由 update_data.js 自动生成，请勿手动编辑
window.__MARKET_DATA__ = {
  "generatedAt": "2026-07-07T03:44:18.136Z",
  "generatedAtDisplay": "2026-07-07 11:44 CST",
  "isPreGenerated": true,
  "date": "2026-07-07",
  "marketData": [
    {
      "name": "上证综指",
      "value": "3,999.03",
      "change": "-1.04%",
      "up": false,
      "live": true,
      "valueRaw": 3999.03,
      "changeRaw": -1.04
    },
    {
      "name": "深证成指",
      "value": "15,259.20",
      "change": "-1.02%",
      "up": false,
      "live": true,
      "valueRaw": 15259.2,
      "changeRaw": -1.02
    },
    {
      "name": "沪深300",
      "value": "4,802.00",
      "change": "-0.83%",
      "up": false,
      "live": true,
      "valueRaw": 4802,
      "changeRaw": -0.83
    },
    {
      "name": "创业板指",
      "value": "3,918.22",
      "change": "-0.78%",
      "up": false,
      "live": true,
      "valueRaw": 3918.22,
      "changeRaw": -0.78
    },
    {
      "name": "恒生指数",
      "value": "23,507.26",
      "change": "-0.46%",
      "up": false,
      "live": true,
      "valueRaw": 23507.26,
      "changeRaw": -0.46
    },
    {
      "name": "日经225",
      "value": "38,912.70",
      "change": "+0.31%",
      "up": true,
      "live": false,
      "valueRaw": null,
      "changeRaw": null
    },
    {
      "name": "S&P 500",
      "value": "5,847.63",
      "change": "+0.54%",
      "up": true,
      "live": false,
      "valueRaw": null,
      "changeRaw": null
    },
    {
      "name": "纳斯达克",
      "value": "19,520.18",
      "change": "+0.91%",
      "up": true,
      "live": false,
      "valueRaw": null,
      "changeRaw": null
    },
    {
      "name": "FTSE 100",
      "value": "8,312.45",
      "change": "-0.18%",
      "up": false,
      "live": false,
      "valueRaw": null,
      "changeRaw": null
    },
    {
      "name": "DAX",
      "value": "18,935.20",
      "change": "+0.47%",
      "up": true,
      "live": false,
      "valueRaw": null,
      "changeRaw": null
    }
  ],
  "recommendations": [
    {
      "code": "000021.SZ",
      "name": "深科技",
      "signal": "关注",
      "signalClass": "hold",
      "position": "3%",
      "positionRaw": 3,
      "holdPeriod": "短线(1-5天)",
      "entry": "54.77",
      "entryRange": "54.50 - 54.93",
      "stopLoss": "45.05",
      "takeProfit": "74.21 (2:1风险回报)",
      "atr": "4.05",
      "framework": "结构分析 | 动量97 | 价值11 | 质量91 | 波动15 | 情绪100 | 统计通过 | 趋势neutral",
      "rationale": "<strong>趋势背景 →</strong>: 趋势=neutral | 价>MA20=是 | MA20斜率=-1.771 | MA20>MA60=是<br><strong>RSI(68)</strong>: 中性 - RSI偏高(68), 追高风险增大<br><strong>谐波形态</strong>: 未检测到标准谐波形态，趋势结构完整<br><strong>因子评分[63分]</strong>: 动量97 | 价值11 | 质量91 | 波动15 | 情绪100<br><strong>统计检验[通过]</strong>: 夏普+6.91, ATR7.4%, 仓位5%→量化折减85%→趋势折减90%<br><strong>量能分析</strong>: 量比(5日)=0.56, 量比(20日)=0.70 [不足]<br><strong>趋势提示</strong>: 趋势中性: 方向不明确, 降低仓位<br><strong>实时行情</strong>: 现价54.77, 涨跌+2.76%, 振幅8.7%, 成交额70.3亿<br><strong>震荡提醒</strong>: 市场处于震荡格局，谐波形态在震荡市中可靠性降低，建议缩小仓位和持仓时间。",
      "live": true,
      "currentPrice": 54.77,
      "changePct": 2.76,
      "confluenceScore": 43,
      "harmonicScore": 15,
      "factorScore": 63,
      "statsPass": true,
      "sharpe": 6.91,
      "correlation": 0.61,
      "harmonicWeight": 6,
      "factorWeight": 21,
      "statsWeight": 24,
      "antiQuantWeight": 0,
      "trendWeight": 2,
      "momentumScore": 97,
      "valueScore": 11,
      "qualityScore": 91,
      "volatilityScore": 15,
      "sentimentScore": 100,
      "patternName": "结构分析",
      "patternDirection": null,
      "pivotCount": 14,
      "quantRegime": {
        "score": 19,
        "regime": "normal",
        "marketType": "ranging",
        "trendEfficiency": 0.46,
        "noiseRatio": 5.38,
        "gapFreq": 12,
        "reversalRate": 0,
        "volCV": 0.19,
        "tailRate": 0,
        "serialCorr": -0.168,
        "breakdown": "量化冲击=19 | 跳空12% | 反转0% | 波CV=0.19 | 肥尾0% | 自相关=-0.168 | 市场=ranging"
      },
      "antiQuantScore": 59,
      "volumeAuthScore": 84,
      "patternStabilityScore": 60,
      "trapRiskScore": 30,
      "antiQuantBreakdown": "量真实性=84 | 形态稳定=60 | 陷阱风险=30",
      "trend": "neutral",
      "trendScore": 36,
      "rsi": 68,
      "volumeConfirmed": false,
      "volSurge": false,
      "volRatio5": 0.56,
      "volRatio20": 0.7
    }
  ],
  "positions": [
    {
      "entryDate": "2026-07-07",
      "code": "600036.SH",
      "name": "招商银行",
      "entryPrice": "38.75",
      "currentPrice": "38.75",
      "currentPriceRaw": 38.75,
      "pnl": "--",
      "pnlClass": "positive",
      "pnlRaw": 0,
      "status": "holding",
      "statusText": "持仓中",
      "action": "持有",
      "actionClass": "hold",
      "daysHeld": 0,
      "expectedRemain": "2-3周",
      "stopLoss": "36.80",
      "atr": 0.85,
      "advice": "沿5日均线稳步上行，谐波形态目标位 43.20 不变。维持当前仓位。",
      "live": false
    },
    {
      "entryDate": "2026-07-07",
      "code": "601899.SH",
      "name": "紫金矿业",
      "entryPrice": "17.62",
      "currentPrice": "17.62",
      "currentPriceRaw": 17.62,
      "pnl": "--",
      "pnlClass": "positive",
      "pnlRaw": 0,
      "status": "add",
      "statusText": "加仓信号",
      "action": "加仓 5%",
      "actionClass": "buy",
      "daysHeld": 0,
      "expectedRemain": "1-2周",
      "stopLoss": "17.80",
      "atr": 0.42,
      "advice": "突破前高确认上行趋势延续，因子模型动量增强。建议加仓 5%。",
      "live": false
    }
  ],
  "history": [
    {
      "date": "2026-05-02",
      "code": "300308.SZ",
      "name": "中际旭创",
      "entry": "115.20",
      "exit": "128.40",
      "pnl": "+11.46%",
      "outcome": "win",
      "result": "止盈触发",
      "days": 12,
      "framework": "谐波蝴蝶 + 动量因子"
    },
    {
      "date": "2026-04-22",
      "code": "688981.SH",
      "name": "中芯国际",
      "entry": "68.50",
      "exit": "72.10",
      "pnl": "+5.26%",
      "outcome": "win",
      "result": "止盈触发",
      "days": 9,
      "framework": "谐波螃蟹 + 均值回归"
    },
    {
      "date": "2026-04-18",
      "code": "601318.SH",
      "name": "中国平安",
      "entry": "48.90",
      "exit": "45.30",
      "pnl": "-7.36%",
      "outcome": "loss",
      "result": "止损触发",
      "days": 15,
      "framework": "谐波加特利 + 质量因子"
    },
    {
      "date": "2026-04-18",
      "code": "600809.SH",
      "name": "山西汾酒",
      "entry": "186.00",
      "exit": "202.50",
      "pnl": "+8.87%",
      "outcome": "win",
      "result": "止盈触发",
      "days": 8,
      "framework": "谐波蝙蝠 + 情绪因子"
    },
    {
      "date": "2026-04-15",
      "code": "002230.SZ",
      "name": "科大讯飞",
      "entry": "42.80",
      "exit": "41.20",
      "pnl": "-3.74%",
      "outcome": "loss",
      "result": "止损触发",
      "days": 11,
      "framework": "谐波螃蟹 + AI因子"
    },
    {
      "date": "2026-04-10",
      "code": "600276.SH",
      "name": "恒瑞医药",
      "entry": "35.60",
      "exit": "39.15",
      "pnl": "+9.97%",
      "outcome": "win",
      "result": "止盈触发",
      "days": 14,
      "framework": "谐波鲨鱼 + 价值因子"
    }
  ],
  "message": "数据由分析引擎于 2026-07-07 11:44 CST 生成"
};
